### ISSUE TITLE
Absolute Path

### ISSUE THREAD

**Issue by irineujunior** [JosephSilber/page-cache#10]
Add / to make absolute path works properly.

https://github.com/JosephSilber/page-cache/blob/master/src/Cache.php#L99

```
return '/' . implode('/', array_filter($paths));
```

Before Fix
![image](https://user-images.githubusercontent.com/260451/37670824-0e51b2f2-2c49-11e8-83bf-32bd697f32dd.png)

After Fix
![image](https://user-images.githubusercontent.com/260451/37670891-2dcb8de2-2c49-11e8-952e-ad28e7efc05c.png)

**Comment by JosephSilber** [comment]
Why isn't it already an absolute path?

The base path comes from the container:

https://github.com/JosephSilber/page-cache/blob/a97a2b3720da0473b600a96c8bfad07e3b3d7898/src/Cache.php#L204-L206

...which [Laravel binds in the `Application` class](https://github.com/laravel/framework/blob/e29b33fe66b3a42f9e2690bd78004bd2851c78f3/src/Illuminate/Foundation/Application.php#L285), which [uses its `basePath`](https://github.com/laravel/framework/blob/e29b33fe66b3a42f9e2690bd78004bd2851c78f3/src/Illuminate/Foundation/Application.php#L377-L380), which [is set in the constructor](https://github.com/laravel/framework/blob/e29b33fe66b3a42f9e2690bd78004bd2851c78f3/src/Illuminate/Foundation/Application.php#L138-L142), which [is passed in via the bootstrapping process](https://github.com/laravel/laravel/blob/29a1739099a2011f5de2a60fccf1c4ac16f007cf/bootstrap/app.php#L14-L16), which uses [PHP's `realpath` function](http://php.net/manual/en/function.realpath.php), which returns an absolute path.

**Comment by irineujunior** [comment]
Actually, the problem apear when we trim the `$path` 
https://github.com/JosephSilber/page-cache/blob/a97a2b3720da0473b600a96c8bfad07e3b3d7898/src/Cache.php#L95-L97

The `$path` come like this

```
dd($path);

array:2 [▼
  0 => "/home/vagrant/Code/Admix/public/page-cache"
  1 => ""
]
```
After `array_map`

```
dd($path);

"home/vagrant/Code/Admix/public/page-cache"
```

Replace `trim` with `rtrim` sound nice too.

```
$paths = array_map(function ($path) {
            return rtrim($path, '/');
        }, $paths);
```

Thanks for Your patience.

**Comment by JosephSilber** [comment]
Good catch :100:
