### ISSUE TITLE
Is possible to not cache authenticated users?

### ISSUE THREAD

**Issue by lfbn** [JosephSilber/page-cache#106]

**Comment by JosephSilber** [comment]
Short answer: no.

The static files are served before Laravel runs. In fact, it doesn't even hit PHP at all.

If you need to customize a page for authenticated users then you should either:

- Make a follow-up AJAX call for that little piece of content, or
- Use a different caching mechanism that _does_ boot up your app

Page cache, by definition, cannot handle this.
