### ISSUE TITLE
Cache tags

### ISSUE THREAD

**Issue by diemah77** [JosephSilber/page-cache#12]
Is there a way to use this package with cache tags so one can flush only parts of the cached requests?

**Comment by tomhorvat** [comment]
I don't think so, because the only identifier is slug.

**Comment by JosephSilber** [comment]
For the fastest response times, these pages are actually cached directly to disk as static files.

When serving a cached file, Laravel never runs. PHP isn't even involved at all. Cached tags don't make sense in this context.

**Comment by diemah77** [comment]
What about tagging/grouping/prefixing the cached files? Is that doable?

**Comment by JosephSilber** [comment]
Not really. The files are stored on disk directly as static files.

The only thing we could maybe add is clearing a subdirectory, but I'm not sure how useful that is.
