### ISSUE TITLE
Purge cache via command? 

### ISSUE THREAD

**Issue by viezel** [JosephSilber/page-cache#13]
Let’s say I want to purge a route or everything because of some business logic. 
Could we create an artisan command for this feature? 

Common usecase would be a website update from the backend, and an observer needs to Purge some cached routes.

**Comment by JosephSilber** [comment]
It's right there in the docs: https://github.com/JosephSilber/page-cache#clearing-the-cache

**Comment by viezel** [comment]
Perfect thanks!
