### ISSUE TITLE
Subdomain cache

### ISSUE THREAD

**Issue by berkneis** [JosephSilber/page-cache#15]
Hi,

I using subdomain route. But all subdomain same request uri. Your plugin confusing address.

My route;
`Route::group(['domain' => '{language}.site.test','middleware' => 'page-cache'], function () {
     Route::group(['as' => 'front.subdomain.', 'namespace' => 'Front'], function ($language) {
        $this->paginate('/', ['as' => 'home', 'uses' => 'SubDomainController@index']);
       // Route::paginate('/', 'SubDomainController@index');
        $this->get('/{slug}', ['as' => 'post', 'uses' => 'SubDomainController@post']);
    });
});`

**Comment by JosephSilber** [comment]
Subdomains are not currently supported. I should probably add that to the docs. Thanks for pointing that out :+1:

**Comment by newalphamedia** [comment]
Unfortunate, I would also like to request subdomains support. Perhaps if a subdomain is present in the url a directory is created based on the subdomain name w/ support for multiple levels of subdomains.
