### ISSUE TITLE
Page not loading from cached file

### ISSUE THREAD

**Issue by jayeshm66** [JosephSilber/page-cache#17]
I am using this plugin,
 page cache is properly created in page cache folder but its not loading from it,

my htaccess as below (puted in htaccess in root not in public)

RewriteCond %{REQUEST_URI} ^/?$
RewriteCond %{DOCUMENT_ROOT}/public/page-cache/pc__index__pc.html -f
RewriteRule .? public/page-cache/pc__index__pc.html [L]
RewriteCond %{DOCUMENT_ROOT}public/page-cache%{REQUEST_URI}.html -f
RewriteRule . public/page-cache%{REQUEST_URI}.html [L]

**Comment by tomerof** [comment]
i have the same problem but i did put it in the public folder.
why did you put it in root ?

**Comment by myurtsev** [comment]
I have the same problem, on every refresh it recreates the html file in stead of loading it.

Content of .htaccess:

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Serve Cached Page If Available...
    RewriteCond %{REQUEST_URI} ^/?$
    RewriteCond %{DOCUMENT_ROOT}/page-cache/pc__index__pc.html -f
    RewriteRule .? page-cache/pc__index__pc.html [L]
    RewriteCond %{DOCUMENT_ROOT}/page-cache%{REQUEST_URI}.html -f
    RewriteRule . page-cache%{REQUEST_URI}.html [L]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

**Comment by theankitjais** [comment]
> I have the same problem, on every refresh it recreates the html file in stead of loading it.
> 
> Content of .htaccess:
> 
> ```
> <IfModule mod_rewrite.c>
>     <IfModule mod_negotiation.c>
>         Options -MultiViews -Indexes
>     </IfModule>
> 
>     RewriteEngine On
> 
>     # Handle Authorization Header
>     RewriteCond %{HTTP:Authorization} .
>     RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
> 
>     # Redirect Trailing Slashes If Not A Folder...
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteCond %{REQUEST_URI} (.+)/$
>     RewriteRule ^ %1 [L,R=301]
> 
>     # Serve Cached Page If Available...
>     RewriteCond %{REQUEST_URI} ^/?$
>     RewriteCond %{DOCUMENT_ROOT}/page-cache/pc__index__pc.html -f
>     RewriteRule .? page-cache/pc__index__pc.html [L]
>     RewriteCond %{DOCUMENT_ROOT}/page-cache%{REQUEST_URI}.html -f
>     RewriteRule . page-cache%{REQUEST_URI}.html [L]
> 
>     # Handle Front Controller...
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteRule ^ index.php [L]
> </IfModule>
> ```

Brother, is your roblem solved? because i am having the same issue
