### ISSUE TITLE
getting cache path not set.

### ISSUE THREAD

**Issue by nikocraft** [JosephSilber/page-cache#19]
I am getting

Exception
Cache path not set.

 
        if (is_null($base)) {
            throw new Exception('Cache path not set.');
        }
 

what could be wrong here? I've tested it locally and it works just fine, but after I uploaded it to ftp it gives me that error.

**Comment by JosephSilber** [comment]
There isn't enough information in this issue to glean any insight into your code. As you said, this works for you locally. You'll have to debug this yourself.

**Comment by icaksama** [comment]
If you using laravel lumen try add this on `bootstrap/app.php`
```
$app->bind('path.public', function () {
    return __DIR__;
});
```
