### ISSUE TITLE
Support for QueryString

### ISSUE THREAD

**Issue by gerbesf** [JosephSilber/page-cache#25]
I made an implementation, but I can not do the merge, because I do not know how to test in Apache, and I do not have the time.

is my suggestion for this functionality.

Replace in method: getDirectoryAndFileNames()

`$segments = explode('/', ltrim($request->getPathInfo().$request->getQueryString(), '/'));`

and use in nginx

` try_files $uri $uri/ /page-cache/$uri$query_string.html/index.php?$query_string;`

**Comment by JosephSilber** [comment]
Query strings don't always signify a unique endpoint (primarily the `utm` ones), which makes including the query string in the cache key very impractical.
