### ISSUE TITLE
Cached pages csrf_token problem

### ISSUE THREAD

**Issue by andreasbakir** [JosephSilber/page-cache#27]
Hi!

First of all what a great package, I have never seen any site load this fast! (Of course serving static html sites is incredibily fast). The only issue I am facing is, that since this package caches a static html version of the corresponding page, the csrf toke in the head is also going to be static. Resulting in broken AJAX calls...

Is there anyway to fix this?

**Comment by JosephSilber** [comment]
Closing as a duplicate of #7.

See [there](https://github.com/JosephSilber/page-cache/issues/7#issuecomment-383564184) for the solution.
