### ISSUE TITLE
 Does not work try_files for main page in nginx

### ISSUE THREAD

**Issue by mezhevikin** [JosephSilber/page-cache#3]
Hello. I use nginx and laravel 5.4. Html file pc__index__pc.html is created in page-cache folder, but nginx does not see it.

My nginx config:

```
     location / {
		try_files $uri $uri/ /page-cache/$uri.html /index.php?$query_string;
	}
	
	location ~ \..*/.*\.php$ {
		# For super-cool-hackers
		return 403;
	}
	
	location ~ \.php$ {
		try_files $uri /index.php =404;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_split_path_info ^(.+\.php)(/.*)$;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
		fastcgi_read_timeout 300;
	}
```

Tell me please, what is wrong?

**Comment by JosephSilber** [comment]
I'm aware of this. Due to server file permissions, I had to make an exception for the main page, and it's cached as `pc__index__pc.html`.

I updated the documentation for Apache, but haven't spent any time with nginx yet to figure out how to route the main request to be server from that saved file.

**Comment by KaelWD** [comment]
This seems to work: 

```
location = / {
	try_files /page-cache/pc__index__pc.html /index.php?$query_string;
}
```

**Comment by YakovGoldberger** [comment]
@KaelWD I followed your suggestion and any subpages would return a 404, I configured the following

```
location = / {
    try_files /page-cache/pc__index__pc.html /index.php/index.php$is_args$args;
}

location / {
    try_files $uri $uri/ /page-cache/$uri.html /index.php?$query_string;
}
```

All working now

**Comment by KaelWD** [comment]
Yeah, my bad, I should have specified that that's in addition to the block in the README.

**Comment by JosephSilber** [comment]
Added it to the docs in https://github.com/JosephSilber/page-cache/commit/3d436bd8acf8857a8962b84d02832c8fffb9e4d0.
