### ISSUE TITLE
Website Url /page-cache/pc__index__pc.html

### ISSUE THREAD

**Issue by ruzgarhasan** [JosephSilber/page-cache#34]
I can also access page-cache / link. is there a way not to be reached?

**Example;**
github.com/page-cache/pc__index__pc.html 

**must be**
github.com/

Note:apache .htaccess

**Comment by JosephSilber** [comment]
Add a redirect match to the `page-cache` directory in your`.htaccess` file:

```
RedirectMatch 403 ^/page-cache
```

**Comment by ruzgarhasan** [comment]
Thank yo 👍 

`RedirectMatch 301 ^/page-cache/(.*)\.html$ /$1`
