### ISSUE TITLE
Not created cached files

### ISSUE THREAD

**Issue by Dayglor** [JosephSilber/page-cache#36]
Hello. 

I'm trying use page-cache and i readed the read.md and i did the step by step, but the laravel do not create cached files... 

No errors show and the file is not created.
My responsecache.php is default.
My Laravel is 5.5.40

**Comment by JosephSilber** [comment]
Can you show the contents of your `app/Http/Kernel.php` file?

**Comment by Dayglor** [comment]
Sorry, my mistake ...
I must have made some confusion and did not change the Kernel ...
Now it's working .... Thank you!

Is there a way to set cache time?

**Comment by JosephSilber** [comment]
The cache lives directly on your disk, not in a Laravel cache, so accessing it doesn't need to boot up the framework.

That's what makes it so lightening fast.

Hence, there's no way to set a cache time. You are free to set up your own schedule to prune your files for older files.

I simply destroy the cache on each deploy, as outlined in the docs.
