### ISSUE TITLE
Dynamic data

### ISSUE THREAD

**Issue by asivaneswaran** [JosephSilber/page-cache#38]
Hi,

I am wondering if I have a page that shows all the articles, how will the package know when to clear the cache? Do I have to clear the cache when there is a new article added to the DB?

Thanks,

**Comment by JosephSilber** [comment]
Correct. You are responsible for clearing the cache.

**Comment by PayteR** [comment]
Whats the best way to invalidate cache? Is there some implementation of invalidation path with wildcard? for example /categories/category-name/* ?

**Comment by Brennii96** [comment]
I'm doing a laravel scheduler to clear the cache every week

**Comment by JosephSilber** [comment]
@PayteR check out #58, which introduced a new `--recursive` flag.
