### ISSUE TITLE
Doesn't show cached files with 'artisan serve'

### ISSUE THREAD

**Issue by KaelWD** [JosephSilber/page-cache#4]
To see cached files using the PHP built-in web server you need to add this to the bottom of `server.php`:

```php
if (file_exists(__DIR__.'/public/page-cache/pc__index__pc.html'))
    require_once __DIR__.'/public/page-cache/pc__index__pc.html';
else
    require_once __DIR__.'/public/index.php';
```

**Comment by KaelWD** [comment]
Ok then, would you prefer it if I submitted a pull request instead?

**Comment by JosephSilber** [comment]
An issue is for... well, issues. You haven't described any issue here, so I closed it.
