### ISSUE TITLE
Suggestions: no-page-cache route middleware and PAGE_CACHE_ENABLED env variable

### ISSUE THREAD

**Issue by bridgeport** [JosephSilber/page-cache#40]
Thanks for this package. Three suggestions:

1) Add a `PAGE_CACHE_ENABLED` environment variable with supporting config file that checks for this. This allows the cache to be turned on and off instead of having to comment out the reference in `Kernel.php`

2) You have a `page-cache` route middleware, but how about doing the inverse: a `no-page-cache` middleware? This'll allow an individual route(s) to be excluded easily while caching everything else by default.

3) Regex cache clearing. Right now, an individual slug can be cleared:
```
php artisan page-cache:clear {slug}
```
But what about extending it to clear a directory, like so:
```
php artisan page-cache:clear country/canada/*
```

Or just clearing anything that matches:
```
php artisan page-cache:clear country/canad*
```

If full-blown regex is too much work to do, at least supporting the asterisk seems to be a reasonable middle ground.

Thanks.

**Comment by KodeStar** [comment]
There is already a PR that was submitted nearly a month ago that will recursively delete a directory, just waiting for it to be merged. https://github.com/JosephSilber/page-cache/pull/58

**Comment by JosephSilber** [comment]
- You can use Laravel's [`withoutMiddleware`](https://laravel.com/docs/8.x/middleware#assigning-middleware-to-routes) on your route, to exclude it from caching:

    ```php
    Route::get('/', 'HomeController@index')->withoutMiddleware('page-cache');
    ```

- To clear a full resource, use [the new `--recursive` flag](https://github.com/JosephSilber/page-cache/pull/58).
