### ISSUE TITLE
What's about problem more then 10000 files in directory on Linux?

### ISSUE THREAD

**Issue by devig** [JosephSilber/page-cache#42]
I have 800 000 of products in my db and routes /product/{product-name}.
I got this problem for product directory.

I think possible solution is - change nginx config:
1) md5(product-name)
2) get 3 left letters and create directory

**Comment by elfeffe** [comment]
Linux doesn’t have that limit, this may be the partition type. Try with EXT4

**Comment by JosephSilber** [comment]
This package intentionally does not do any computation at all when fetching a file from the filesystem.

If you cannot structure your URLs to only contain the maximum number of entries allowed by your filesystem, I think you'd be better of with a different caching mechanism.
