### ISSUE TITLE
Use .json file extension instead of .html for JSON responses

### ISSUE THREAD

**Issue by andypa** [JosephSilber/page-cache#52]
Hi Joseph,

I was wondering if you would accept a PR which adds the ability to store a response in a .json file instead of a .html, if the response itself is a JSON document. The reason behind it is that the content-type in the browser would automatically be correct.

Let me know what you think about it.

Cheers!

**Comment by JosephSilber** [comment]
Sounds great 👍

**Comment by andypa** [comment]
Hi @JosephSilber 

the PR is here: https://github.com/JosephSilber/page-cache/pull/53

Open for any kind of improvements :)

Have a great day (in these rather difficult times).

Best regards,
Andy

**Comment by JosephSilber** [comment]
The related PR was merged a couple of weeks ago.
