### ISSUE TITLE
Partial slug cache clearing

### ISSUE THREAD

**Issue by KodeStar** [JosephSilber/page-cache#57]
Is it possible to use part of a slug to clear the cache?

My url looks like `domain/section/id/item-name` when something on the page is changed I'm running `Artisan::call('page-cache:clear section/'.$id.'/'.$item->url);` which works perfectly unless the thing that has changed is the $item->url then both item-name.hml and item-name-new.html exist and I can't 301 the old to the new because the old exists so gets returned.

If I could run `Artisan::call('page-cache:clear section/'.$id);` instead and clear everything in `page-cache\section\id` that would be a lot more flexible.

**Comment by KodeStar** [comment]
Maybe instead of
```
    public function clear()
    {
        return $this->files->deleteDirectory($this->getCachePath(), true);
    }
```
```
    public function clear($slug = '')
    {
        return $this->files->deleteDirectory($this->getCachePath($slug), true);
    }
```

**Comment by JosephSilber** [comment]
Let's keep this discussion going in the PR.
