### ISSUE TITLE
Could not find package silber/page-cache at any version for your minimum-stability (stable)

### ISSUE THREAD

**Issue by imannms** [JosephSilber/page-cache#6]
I run `php composer.phar require silber/page-cache`

then the result is:

> Could not find package silber/page-cache at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

PHP7
Nginx
Ubuntu 16.04
Laravel 5.4.28

**Comment by infostreams** [comment]
I ran into the same issue. You should type 

```
composer require silber/page-cache:dev-master
```

instead. @JosephSilber You should add version tags to your (i.e. "v1.0.0") to your repository... perhaps they were accidentally deleted?

**Comment by JosephSilber** [comment]
Just tagged `v1.0.0` :1st_place_medal:
