### ISSUE TITLE
Tests without assertions

### ISSUE THREAD

**Issue by mvdnbrk** [JosephSilber/page-cache#63]
The following tests don't have any assertions:

- Silber\PageCache\Tests\CacheTest::testCachesRootToSpecialFilename
- Silber\PageCache\Tests\CacheTest::testCachesJsonResponsesWithJsonExtension

**Comment by JosephSilber** [comment]
Because they have expectations.

**Comment by mvdnbrk** [comment]
Can be me, I dont see them. PHP unit will complain about this on versions `>4.8`
