### ISSUE TITLE
How to clear cache for only file "pc __index__ pc.html"

### ISSUE THREAD

**Issue by caocanhlinh** [JosephSilber/page-cache#68]
I need to clear cache for url as the homepage because it is regularly updated. Thanks

**Comment by jberculo** [comment]
Not tested, but you could try:

```
$cache = app()->make(Cache::class);
$cache->forget('/');
```

And e.g. add that to an observer that detects a model save

**Comment by caocanhlinh** [comment]
php artisan page-cache:clear pc__index__pc
