### ISSUE TITLE
csrf

### ISSUE THREAD

**Issue by monovm** [JosephSilber/page-cache#7]
how about pages contains csrf token ?

**Comment by monovm** [comment]
i think solution is this 
give variable to token value in form when we want create cache 
then when we want to send cached version to view we can give value to variable. 
i think in this way packge will support pages with csrf token too.

**Comment by JosephSilber** [comment]
CSRF tokens are never used for GET requests, which are [the only type of requests cached](https://github.com/JosephSilber/page-cache/blob/3d436bd8acf8857a8962b84d02832c8fffb9e4d0/src/Cache.php#L110-L113) by this package.

**Comment by bussnet** [comment]
Issue should reopen. The problem here is the token in the <input> field or in the meta-head on an (GET requested) site which want to post a form. If this is cached, all users use the same token.

**Comment by JosephSilber** [comment]
If your page contains information specific to a single user, then you can't cache it. It's as simple as that. Don't use the package's middleware on that route.

**Comment by JosephSilber** [comment]
Another option would be to have a special non-cached API route that returns the CSRF token. For example:

```php
// Make sure this route odes not have the page-cache middleware
Route::get('csrf', function () {
    return csrf_token();
});
```
Then in your JS:

```js
async function submitOrder() {
    window.axios.defaults.headers.common['X-CSRF-TOKEN'] = await axios.get('csrf');
}
```
