### ISSUE TITLE
Disabling or dev mode

### ISSUE THREAD

**Issue by warmwhisky** [JosephSilber/page-cache#71]
Hey, do you have any advice on a way to pypass when in dev or local?

**Comment by rajakhoury** [comment]
See this [example](https://github.com/JosephSilber/page-cache#customizing-what-to-cache)
What you could do is add a check e.g if `! config('app.debug')` then return false. Make sure to clear all cahed pages so the request can hit your app.

**Comment by JosephSilber** [comment]
What @rajakhoury said.

Also note: even without disabling it, you still won't be served the cached files unless you update your Apache/nginx settings locally.

**Comment by warmwhisky** [comment]
@rajakhoury  @JosephSilber 
Thanks for the pointers. I ended up removing the entires from Apache htaccess for local then used gitignore and removed it from the git index.
