### ISSUE TITLE
Feature Request: Automatically delete cached file with model changes

### ISSUE THREAD

**Issue by sarfraznawaz2005** [JosephSilber/page-cache#84]
Any plan to add automatic cache-purge facility when corresponding model changes for a page. For example, we can tell package which routes we want to cache:

````
// example-package-config
return [
   // routeName => [one ore more model paths]
    'home' => App\Models\Post::class,
    'category.index' => [App\Models\Post::class, App\Models\Category::class],
];
````

Using something like above, the cached page of homepage will be automatically deleted when there is any change in Post mode. (using model events for example) and will be cached again when page is visited again. Similarly, cached page of category listing page will be deleted when there is change in either model Post or the model Category.

Would also be cool if cache key is made with logged in user id (if logged in) so each user gets his/her own cached content only.

I am not sure if this fits for this package but one thing is for sure that if we have full page cache thing with auto-deletion, laravel community would embrace it fully for obvious speed benefits.

**Comment by JosephSilber** [comment]
This is quite trivial to add on your own:

```php
use Silber\PageCache\Cache;

class Post extends Model
{
    public static booted()
    {
        static::updated(fn ($post) => app(Cache::class)->forget("posts/{$post->id}"));
        static::deleted(fn ($post) => app(Cache::class)->forget("posts/{$post->id}"));
    }
}
```
