### ISSUE TITLE
Handling different top level domains

### ISSUE THREAD

**Issue by lamalamaMark** [JosephSilber/page-cache#85]
Our application is served via 4 different domains with different locales. For as far as we can see it's not possible to handle this situation. Nonetheless I wanted to check if you have handled this situation before? If not we will make a fork / PR for this feature :)

**Comment by JosephSilber** [comment]
You can easily accomplish this by extending the `Cache` class, and overwriting the [`getDirectoryAndFileNames`](https://github.com/JosephSilber/page-cache/blob/49bd7c933d1b940a8136399591e92ecb4b5ead74/src/Cache.php#L197) method to prepend the domain name.

You will also have to properly configure your nginx script to account for that.

**Comment by MarcosBL** [comment]
You can also do it setting a different path depending on locale at boot on AppServiceProvider 

Look here https://github.com/JosephSilber/page-cache/issues/74#issuecomment-883701867
