### ISSUE TITLE
cache web and mobile version separately

### ISSUE THREAD

**Issue by fadbad** [JosephSilber/page-cache#87]
We use this package for a magazine and it's awesome, we have a problem with serving google ads as we need to separate  mobile views from web views.

Is there any plans to support such issues??
We are doing some developments, but till now the htaccess is not working fine for us.
Please advise

**Comment by JosephSilber** [comment]
There's no plan to add this to the core.

---

To add this yourself to your app, see https://github.com/JosephSilber/page-cache/issues/85#issuecomment-901196655

**Comment by MarcosBL** [comment]
You can also do it setting a different path depending on mobile/web at boot on AppServiceProvider 

Look here https://github.com/JosephSilber/page-cache/issues/74#issuecomment-883701867
