### ISSUE TITLE
Compatibility with Laravel 5.5

### ISSUE THREAD

**Issue by irineujunior** [JosephSilber/page-cache#9]
Hi, can you please update composer.json to support laravel 5.5

```
"symfony/http-foundation": "^2.6.0|^3.0.0|^4.0.0"
```

Thanks

**Comment by JosephSilber** [comment]
Removing support for Symfony 3 was a mistake. Fixed in https://github.com/JosephSilber/page-cache/commit/b2bfe2dd45b04c29bbba0ea7ed8e9e3e431d1789.
